dist: xenial
language: python
python:
  - 3.4
  - 3.6
  - 3.7
before_install: pip install --upgrade setuptools
install: pip install tox tox-travis coveralls
before_script: if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then tox -e flake8; fi
script: tox -r
after_success: coveralls
sudo: false
