site_url: https://chimpler.github.io/pytcher/
site_author: Francois Dang Ngoc
# Repository
repo_name: chimpler/pytcher
repo_url: https://github.com/chimpler/pytcher
site_name: pytcher
nav:
    - Home: index.md
    - Install: install.md
    - Route: route.md
    - Marshalling: marshalling.md
    - Unmarshalling: unmarshalling.md
    - Exception: exception.md
    - WSGI: wsgi.md
    - Test: test.md
theme: material
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          guess_lang: false
    - pymdownx.superfences
    - pymdownx.inlinehilite


extra_css: [extra.css]
