site_url: https://chimpler.github.io/pytcher/
site_author: Francois Dang Ngoc
repo_name: chimpler/pytcher
repo_url: https://github.com/chimpler/pytcher
site_name: pytcher
nav:
    - Home: index.md
    - User Guide:
        - Getting Started: quickstart.md
        - Install: install.md
        - Route: route.md
        - Marshalling: marshalling.md
        - Unmarshalling: unmarshalling.md
        - Exception: exception.md
        - WSGI: wsgi.md
        - Test: test.md
    - API:
        - Pytcher: api/pytcher.md
        - App: api/app.md
        - Request: api/request.md
        - Matchers: api/matchers.md
        - Test: api/app.md
theme: material
extra_javascript: [extra.js]
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          guess_lang: false
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - markdown_include.include
