site_name: pytcher
nav:
    - Home: index.md
    - Install: user/install.md
    - Quick start: user/quickstart.md
    - Examples: user/example.md
    - Route: user/route.md
    - Marshalling: user/marshalling.md
    - Unmarshalling: user/unmarshalling.md
    - Exception: user/exception.md
    - WSGI: user/wsgi.md
    - Test: user/test.md
theme: material
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          guess_lang: false

extra_css: [extra.css]
